# Generated by Django 5.0.4 on 2024-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ver_comidas',
            name='categorias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ver_comidas',
            name='comidas',
            field=models.CharField(max_length=50),
        ),
    ]
