# Generated by Django 5.0.4 on 2024-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_ver_sugerencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ver_sugerencias',
            name='sugerencia_numero',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
