# Generated by Django 5.0.6 on 2024-06-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_ver_sugerencias_sugerencia_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ver_sugerencias',
            old_name='fecha_publicación',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='ver_sugerencias',
            old_name='sugerencia_numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='ver_sugerencias',
            old_name='comida_categoria_picante',
            new_name='pedido',
        ),
    ]
