# Generated by Django 5.0.6 on 2024-06-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_rename_fecha_publicación_ver_sugerencias_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ver_sugerencias',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=5, unique=True),
        ),
    ]
